/**
 * Lighthouse audit runner for Daydream Dex.
 *
 * Runs Lighthouse against representative URLs on production and writes
 * per-page JSON results plus a summary markdown.
 *
 * Targets:
 *  - Performance     >= 90
 *  - Accessibility   >= 90
 *  - Best Practices  >= 90
 *  - SEO             >= 95
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const RESULTS_DIR = resolve(__dirname, 'results');
const SUMMARY_PATH = resolve(__dirname, '../../../notes/lighthouse-results.md');

const BASE = 'https://daydreamdex-astro.pages.dev';
const PAGES = [
  { name: 'homepage', url: `${BASE}/` },
  { name: 'about', url: `${BASE}/about` },
  { name: 'coaching', url: `${BASE}/coaching` },
  {
    name: 'article-python-career',
    url: `${BASE}/blog/2024-08-04-python-career-transition-guide-and-experience`,
  },
];

const TARGETS = {
  performance: 90,
  accessibility: 90,
  'best-practices': 90,
  seo: 95,
};

async function runAudits() {
  let lighthouse;
  let chromeLauncher;
  try {
    ({ default: lighthouse } = await import('lighthouse'));
    chromeLauncher = await import('chrome-launcher');
  } catch (err) {
    console.error(
      '[lighthouse] dependencies not installed. Skipping audits.\n' +
        'Install with: npm install -D lighthouse chrome-launcher',
    );
    console.error(err.message);
    process.exit(0); // soft exit so test:all does not fail
  }

  mkdirSync(RESULTS_DIR, { recursive: true });
  mkdirSync(dirname(SUMMARY_PATH), { recursive: true });

  const chrome = await chromeLauncher.launch({
    chromeFlags: ['--headless=new', '--no-sandbox'],
  });

  const date = new Date().toISOString().slice(0, 10);
  const summary = [];

  for (const { name, url } of PAGES) {
    console.log(`[lighthouse] auditing ${name} -> ${url}`);
    const runnerResult = await lighthouse(url, {
      port: chrome.port,
      output: 'json',
      logLevel: 'error',
      onlyCategories: ['performance', 'accessibility', 'best-practices', 'seo'],
    });

    const lhr = runnerResult.lhr;
    const scores = Object.fromEntries(
      Object.entries(lhr.categories).map(([k, v]) => [k, Math.round((v.score ?? 0) * 100)]),
    );

    const filename = `${name}-${date}.json`;
    writeFileSync(
      resolve(RESULTS_DIR, filename),
      JSON.stringify(lhr, null, 2),
    );

    summary.push({ name, url, scores });
    console.log(`[lighthouse] ${name}:`, scores);
  }

  await chrome.kill();

  // Write markdown summary
  const lines = [
    `# Lighthouse Results — ${date}`,
    '',
    `Targets: Performance >= ${TARGETS.performance}, Accessibility >= ${TARGETS.accessibility}, Best Practices >= ${TARGETS['best-practices']}, SEO >= ${TARGETS.seo}`,
    '',
    '| Page | Performance | Accessibility | Best Practices | SEO |',
    '| --- | ---: | ---: | ---: | ---: |',
  ];
  for (const row of summary) {
    const mark = (k) => {
      const v = row.scores[k] ?? 0;
      const ok = v >= TARGETS[k];
      return `${v}${ok ? '' : ' ⚠'}`;
    };
    lines.push(
      `| ${row.name} | ${mark('performance')} | ${mark('accessibility')} | ${mark('best-practices')} | ${mark('seo')} |`,
    );
  }
  lines.push('', `Generated by tests/lighthouse/audit.js`);
  writeFileSync(SUMMARY_PATH, lines.join('\n'));
  console.log(`[lighthouse] summary -> ${SUMMARY_PATH}`);
}

runAudits().catch((err) => {
  console.error(err);
  process.exit(1);
});
